// GENERATED from dji_link_beta/diag_codes_full.py (DIAGCODE_TEXT, resolved
// tips > capsule > checklist). DiagnosticCode(int) -> bundled English text.
// Do not edit by hand; regenerate if the Python table changes.
#include "core/diag_codes.hpp"

#include <map>

namespace djilink {
namespace {

const std::map<int, const char*> kDiagText = {
    {10001, "Camera malfunction"},
    {10012, "Camera overheating. Wait for camera temperature to return to normal before use."},
    {10014, "Camera USB connected"},
    {10015, "Camera not encrypted. Contact DJI Support for assistance"},
    {10016, "Camera not calibrated. Image quality affected. Contact DJI Support for assistance"},
    {10017, "Camera not calibrated. Image quality affected. Contact DJI Support for assistance"},
    {10018,
     "Camera RCAM not connected. Image quality affected. Contact DJI Support for assistance"},
    {10019, "%1$s"},
    {10022, "No SD card"},
    {10023, "SD card malfunction"},
    {10024, "Disable SD card read and write protection or change card"},
    {10025, "File system error. Chang SD card"},
    {10027, "SD card full. Change card or delete files"},
    {10028, "SD card speed low. Normal use may be affected. Replace SD card"},
    {10030, "File number limit on SD card exceeded. Back up files and format storage"},
    {10031, "Preparing..."},
    {10034,
     "SD card speed low. Normal use may be affected. Back up files and format or replace SD card"},
    {10035, "Insufficient SD card space. Change SD card or delete files"},
    {10038, "Camera overheated. Recording stopped. Allow camera to cool down before use"},
    {10039, "The camera restarted abnormally, please contact your camera colleague"},
    {10056, "Insufficient camera storage. Shooting failed"},
    {10057,
     "SD card speed low. Normal use may be affected. Back up files and format or replace SD card"},
    {10058, "Internal storage lifespan reached. Replace promptly. Continued use may lead to loss "
            "of stored files"},
    {10060, "Storage unavailable"},
    {10061, "File system error. Back up file and format aircraft storage"},
    {10062, "Aircraft storage full. Back up file and clear space"},
    {10071, "SD card formatting required"},
    {10072, "Internal storage formatting required"},
    {10073, "Internal storage formatting required"},
    {10074, "Formatting SD card..."},
    {10075, "Formatting internal storage..."},
    {10076, "Formatting internal storage..."},
    {10077, "File system error"},
    {10078, "Aircraft storage full. Back up file and clear space"},
    {10079,
     "File number limit on aircraft internal storage exceeded. Back up files and format storage"},
    {10080,
     "File number limit on aircraft internal storage exceeded. Back up files and format storage"},
    {10081, "Aircraft internal storage speed low. Back up files and format storage"},
    {10082, "Aircraft internal storage speed low. Back up files and format storage"},
    {10083, "Camera storage speed low. Back up file and format storage space"},
    {10087, "Internal storage severely fragmented. Back up files and format internal storage"},
    {10088, "Unable to load internal storage status info"},
    {10089, "Internal storage error. Contact DJI Support"},
    {10090, "Aircraft internal storage error. Contact DJI Support"},
    {10091, "Aircraft internal storage error. Contact DJI Support"},
    {10092, "Insufficient storage on aircraft. Free up space and try again"},
    {10093, "Failed to write video to storage. Recording will stop soon"},
    {10094, "Storage write speed slow. Shooting will stop soon"},
    {10095, "Storage full. Recording will stop soon"},
    {10096, "Camera malfunction"},
    {10098, "SD card unavailable. Connect to computer to back up files and format SD card"},
    {10099, "Aircraft internal storage unavailable. Connect to computer to back up files and "
            "format storage"},
    {10100, "Aircraft internal storage unavailable. Connect to computer to back up files and "
            "format storage"},
    {10101, "Camera lens error"},
    {10103, "Camera not calibrated. Image quality affected. Contact DJI Support for assistance"},
    {30001, "In flight"},
    {30002, "No satellite positioning. Fly with caution"},
    {30003, "In flight"},
    {30004, "Attitude mode. Fly with caution"},
    {30005, "Takeoff permitted"},
    {30006, "Takeoff permitted"},
    {30007, "Take off with caution (Attitude mode)"},
    {30008, "Take off with caution (no satellite positioning)"},
    {30013, "Altitude Zone %1$s"},
    {30014, "Satellite positioning signal weak (Max altitude %1$s)"},
    {30015, "In flight"},
    {30016, "Attitude mode (Max altitude %1$s )"},
    {30020, "Aircraft in Attitude mode. Unable to hover. Fly with caution"},
    {30021,
     "Compass interference. No satellite positioning or vision positioning. Fly with caution"},
    {30022, "Aircraft in Attitude mode. Unable to hover. Fly with caution"},
    {30024, "Returning to home"},
    {30025, "Returning to home"},
    {30026, "Returning to home"},
    {30027, "Returning to home"},
    {30028, "Returning to home"},
    {30029, "Signal lost. Disconnected from aircraft"},
    {30030, "Signal lost"},
    {30031, "Return to home canceled"},
    {30032, "Critical low battery"},
    {30033, "Critically low battery. Aircraft landing automatically. Use control sticks to help "
            "aircraft avoid obstacles or adjust landing position"},
    {30034, "Critical low battery voltage"},
    {30035, "Critical low battery voltage. Aircraft landing automatically"},
    {30037, "Sensor error"},
    {30038, "ESC error"},
    {30039, "Sensor error"},
    {30040, "Sensor error"},
    {30041, "Sensor error"},
    {30042, "Sensor error"},
    {30043, "Sensor error"},
    {30044, "Sensor error"},
    {30045, "Sensor error"},
    {30046, "Sensor error"},
    {30047, "Sensor error"},
    {30048, "Sensor Error"},
    {30049, "Satellite positioning signal weak"},
    {30050, "IMU calibration required"},
    {30051, "Preparing to take off"},
    {30053, "IMU initialization failed"},
    {30054, "IMU initialization failed"},
    {30055, "IMU calibration required"},
    {30056, "IMU calibration required"},
    {30057, "Sensor error. Restart aircraft"},
    {30058, "IMU hardware malfunction"},
    {30059, "Compass initialization failed"},
    {30060, "Compass calibration required"},
    {30062, "Compass calibration required"},
    {30063, "Compass initialization failed"},
    {30064, "Unable to take off"},
    {30065, "Unable to take off (no satellite positioning)"},
    {30066, "Preparing to take off"},
    {30067, "Preparing to take off"},
    {30068, "Battery installation error. Aircraft unable to take off. Ensure battery is installed "
            "properly"},
    {30069, "Connecting to DJI Assistant 2"},
    {30070, "Aircraft being locked"},
    {30071, "IMU installation error"},
    {30072, "Preparing to take off"},
    {30074, "Battery cell error"},
    {30075, "Battery communication error"},
    {30076, "Critical low voltage. Charge battery promptly"},
    {30077, "Critical low battery"},
    {30078, "Charging battery required"},
    {30079, "Low battery"},
    {30080, "Preparing to take off"},
    {30081, "Flight Simulator running"},
    {30082, "Aircraft pitch angle too large"},
    {30084, "IMU initialization failed"},
    {30085, "ESC error"},
    {30086, "Running Flight Simulator. Unable to take off. Restart aircraft"},
    {30087, "Aircraft pitch angle too large"},
    {30088, "Sensor malfunction"},
    {30089, "Sensor malfunction"},
    {30090, "Sensor malfunction"},
    {30091, "Sensor malfunction"},
    {30092, "Sensor value error"},
    {30093, "Sensor value error"},
    {30094, "Sensor value error"},
    {30095, "Sensor value error"},
    {30096, "Compass calibration required"},
    {30097, "IMU calibration required"},
    {30098, "No satellite positioning module"},
    {30099, "Recorded data error"},
    {30100, "Sensor not detected"},
    {30101, "RC calibration required"},
    {30102, "RC calibration required"},
    {30103, "RC calibration required"},
    {30104, "RC calibration required"},
    {30105, "Navigation system error"},
    {30106, "Aircraft missing parts"},
    {30107, "RC calibration required"},
    {30108, "Data acquisition error"},
    {30109, "Restart aircraft"},
    {30110, "Aircraft rolled over"},
    {30111, "Motor stuck. Check for objects blocking motor or contact DJI Support for assistance"},
    {30112, "Load unbalanced"},
    {30113, "Motor idle. Unable to take off. Check whether propellers are detached or installed "
            "incorrectly."},
    {30114, "Starting motor failed"},
    {30115, "Unable to take off"},
    {30116, "Excessive aircraft rollover time"},
    {30117, "Battery firmware version error"},
    {30121, "Satellite positioning error"},
    {30122, "Aircraft firmware version out-of-date"},
    {30123, "Takeoff altitude error"},
    {30124, "Inconsistent ESC version"},
    {30125, "IMU installation error"},
    {30127, "Compass installation error"},
    {30128, "Motor beeping..."},
    {30129, "ESC overheating"},
    {30130, "Aircraft impacted. Propellers stopped"},
    {30132, "Aircraft restart required"},
    {30133, "Battery firmware version out-of-date"},
    {30134, "Battery voltage difference too large"},
    {30135, "Aircraft processor chip overheating"},
    {30138, "Throttle control stick off-centered. Ensure throttle control stick remains centered "
            "during auto takeoff."},
    {30140, "Battery level error"},
    {30142, "Motor unable to rotate. Check motor"},
    {30143, "Motor load unbalanced. Check motor mounts"},
    {30144, "Propellers not installed"},
    {30145, "Motor fails to rotate. Unfold propellers and check for obstructions. Wait until motor "
            "cools down and try again"},
    {30149, "Strong wind warning. Aircraft unable to return to home automatically. Lower altitude "
            "immediately and return to home manually"},
    {30150, "Propeller malfunction. Check whether correct propellers are being used."},
    {30151, "Propeller malfunction. Check whether correct propellers are being used."},
    {30152, "Current elevation above %1$s. Fly with caution"},
    {30154, "Propeller guard detected. Flight performance reduced. Battery consumption will "
            "increase. Auto RTH and auto landing will trigger earlier"},
    {30155, "Water detected below aircraft. Minimum flight altitude adjusted to 1 m."},
    {30156, "Flight Data Reading mode enabled"},
    {30157, "Aircraft core board overheating. Power off aircraft and wait for temperature to "
            "return to normal."},
    {30163, "Motor error. Check propellers and fly with caution"},
    {30165, "Motor unable to rotate. Check for objects blocking motor or contact DJI Support for "
            "assistance."},
    {30166, "Motor idle. Check whether propellers are installed"},
    {30167, "Aircraft attitude angle too large. Ensure the aircraft is level and restart it."},
    {30168, "Max power load reached. Fly with caution"},
    {30183, "%1$s"},
    {30184, "Low battery. Returning to home"},
    {30185, "Aircraft overheated. Automatically returning to home"},
    {30200, "Auto returning to home..."},
    {30209, "ESC short-circuited. Restart aircraft"},
    {30210, "Power system hardware error. Restart aircraft"},
    {30211, "Incompatible battery version. Change battery"},
    {30212, "Non-DJI battery"},
    {30213, "Home Point updated. RTH altitude adjusted to %1$s"},
    {30214, "Satellite positioning signal weak. Flight altitude limited. Wait for aircraft to gain "
            "satellite positioning signal before ascending"},
    {30216, "Compass interference. Altitude limit set. Calibrate compass to continue ascending"},
    {30217, "Gimbal calibrating"},
    {30218, "Battery version update required"},
    {30219, "Flight control system error"},
    {30220, "Compass connection error"},
    {30222, "Aircraft activation required"},
    {30223, "Updating"},
    {30224, "Aircraft module firmware versions do not match"},
    {30225, "Aircraft restart required"},
    {30226, "Unable to take off"},
    {30227, "Aircraft overheating. Power errors may occur. Return to home promptly"},
    {30228, "Aircraft temperature too low. Power errors may occur. Return to home promptly"},
    {30229, "Payload mode enabled. Return aircraft to an area nearby the home point promptly and "
            "fly in a wind-free environment to ensure flight safety"},
    {30230, "%1$s"},
    {30231, "Extra payload detected. Return aircraft to an area nearby the home point promptly and "
            "fly in a wind-free environment to ensure flight safety"},
    {30232, "%1$s"},
    {30234, "ESC short-circuited. Restart aircraft"},
    {30235, "Takeoff altitude error"},
    {30236, "Aircraft impacted. Propellers stopped"},
    {30237, "Flight altitude restricted. Log in or go to real-name authentication"},
    {30238, "High altitude. Fly with caution"},
    {30239, "Unable to take off (no satellite positioning)"},
    {30240, "Ascending and returning to home..."},
    {30241, "Auto returning to home..."},
    {30242, "Auto returning to home..."},
    {30243, "Descending and returning to home..."},
    {30244, "Aircraft satellite positioning interference. Aircraft unable to fly stably. Land or "
            "RTH promptly"},
    {30245, "Aircraft satellite positioning interference. Aircraft unable to fly stably. Land or "
            "RTH promptly"},
    {30246, "Propeller error. Check if propeller on beeping motor is warped or damaged. If so, "
            "power off aircraft, replace propeller, and restart aircraft"},
    {30248, "Home Point updated. RTH altitude adjusted to %1$s"},
    {30251, "Check Propeller Installation"},
    {30252, "Propeller Installation Error"},
    {30253, "Calibrating IMU..."},
    {30254, "Aircraft connected to USB"},
    {30255, "Aircraft returning to home. Controlling aircraft via control sticks not supported"},
    {30256, "Control stick pushed down. Aircraft flying backward. Aircraft RTH canceled"},
    {30257, "Control stick pushed down. Aircraft descending. Aircraft RTH canceled"},
    {30259, "Home Point in Altitude Zone. Aircraft will return at lower altitude"},
    {30260, "Controller battery level low"},
    {30262,
     "Max flight distance reached. Go to Settings > Safety to adjust max distance if needed"},
    {30263, "Flight distance restricted. Log in or complete real-name authentication"},
    {30266, "It is recommended to switch to N mode during RTH for extended flight time"},
    {30267, "Max flight distance reached"},
    {30269, "Aircraft satellite positioning error"},
    {30270, "Unable to take off. Update Fly Safe database. Contact DJI Support if issue persists"},
    {30272, "Propellers folded. Unable to take off"},
    {30273, "ESC temperature too low"},
    {30274, "Battery output power insufficient"},
    {30275, "Aircraft system overloaded"},
    {30276, "Aircraft system memory low"},
    {30278, "Aircraft movement detected"},
    {30279, "Flight altitude restricted"},
    {30282, "Vision sensors error"},
    {30283, "ToF sensor error"},
    {30284, "Vision system error"},
    {30285, "Firmware update required"},
    {30286, "Fly Safe database requires update"},
    {30289, "Preparing to take off..."},
    {30290, "Restart aircraft"},
    {30291, "Preparing to take off..."},
    {30292, "Firmware update required"},
    {30293, "Reinstall battery"},
    {30294, "Gimbal error"},
    {30295, "Gimbal error"},
    {30297, "RC signal lost. Unable to take off"},
    {30298, "RC signal lost. Unable to take off"},
    {30299, "Take off again within %1$ss"},
    {30300, "Current battery level may be too low for aircraft to return to home. Plan ahead for "
            "an open area to land if necessary"},
    {30301, "Battery level low. Return to home"},
    {30302, "Max Flight Speed Reached. Update your aircraft firmware."},
    {30303, "Motor overloaded. Land promptly or cancel takeoff. Check whether motor and propellers "
            "are blocked or have frozen"},
    {30304, "Motor voltage too high"},
    {30305, "Motor voltage too low"},
    {30306, "Unable to take off"},
    {30307, "RTH stopped"},
    {30309, "RTH stopped"},
    {30310,
     "ESC overheated. Flight performance reduced. Return to home promptly and wait for aircraft to "
     "cool down before next flight. Contact after-sales service if issue persists"},
    {30311, "High altitude. Fly with caution"},
    {30312, "High altitude.Aircraft may be unable to maintain altitude due to insufficient power. "
            "Continuing to fly not recommended"},
    {30315, "Disable Sideways Flight enabled. Go to Settings > Safety to disable this feature"},
    {30316, "Land aircraft and remove gimbal protector to ensure flight safety"},
    {30317, "ESC severely overheated. Forced RTH initiated. Wait for aircraft to cool down before "
            "next flight"},
    {30318, "Motor stalled. Return to home promptly and check if motor is blocked"},
    {30319, "Check propellers"},
    {30331, "Remote ID functionality normal"},
    {30332, "Remote ID error"},
    {30333, "Remote ID error"},
    {30334, "Remote ID error"},
    {30337, "Aircraft not in flight. Cruise control disabled"},
    {30338, "Switching flight modes. Cruise control disabled"},
    {30339, "Aircraft braking. Cruise control disabled"},
    {30340, "Flight speed limited. Cruise control disabled"},
    {30341,
     "Aircraft approaching the set max flight altitude or distance. Cruise control disabled"},
    {30342, "Cruise control unavailable in current flight mode. Cruise control disabled"},
    {30343, "Aircraft braking. Cruise control disabled"},
    {30344, "Remote controller signal lost. Cruise control disabled"},
    {30345, "Aircraft in cruise control"},
    {30346, "Satellite positioning signal weak. Geo-awareness function degraded. Fly with caution"},
    {30347, "Failed to load dynamic safety data. Geo-awareness function degraded. Go to Settings > "
            "About to update FlySafe data"},
    {30348, "Failed to query dynamic safety data. Geo-awareness function degraded"},
    {30349, "Satellite positioning signal weak. Geo-awareness function degraded. Fly with caution"},
    {30350, "ECO"},
    {30351, "Aircraft weighs over 250 g with current battery installed. Not compliant with EU "
            "regulations for C0 labeled drones"},
    {30352,
     "Propeller guard installed. Aircraft not compliant with EU regulations for C0 labeled drones"},
    {30353, "DJI Cellular Dongle installed. Aircraft not compliant with EU regulations for "
            "C0 labeled drones"},
    {30354, "Remote controller update required"},
    {30356, "FlySafe data density high in current region. Aircraft may not be able to fully "
            "process data. It is recommended to update FlySafe database"},
    {30357, "Inconsistent safety database versions between app and aircraft. Update database"},
    {30360,
     "Flight altitude is limited when propeller guards are installed in high-altitude areas"},
    {30361, "Remove propeller guards before taking off in high-altitude areas"},
    {30362, "Altitude of current location is too high. Do not install propeller guard and fly with "
            "caution"},
    {30363, "High wind speed detected. It is recommended to switch to landscape mode or reduce "
            "gimbal attitude angle for stability"},
    {30365, "ESC voltage too low. Replace battery"},
    {30366, "Device unavailable"},
    {30367, "Device info expired"},
    {30368, "No subject found. Unable to start"},
    {30369, "Severe signal interference"},
    {30371, "\"Flight controller error. Aircraft will land in current position\nUse control sticks "
            "to help aircraft avoid obstacles during descent\""},
    {30380,
     "Operational identification broadcast pending. Connect controlling device to internet or go "
     "to Settings > Safety > Aircraft Operational Identification Broadcast to connect aircraft"},
    {30629, "Max altitude for RC Track control reached"},
    {30630, "Max distance for RC Track control reached"},
    {30631, "No GPS for RC Track. Unable to refresh Dynamic Home Point"},
    {30632, "RC Track has entered Restricted Zone. Unable to refresh Dynamic Home Point"},
    {30633, "RC Track has left Restricted Zone. Refreshing Dynamic Home Point"},
    {30634, "RC Track signal lost. Unable to refresh Dynamic Home Point"},
    {30635, "RC Track connected. Refreshing Dynamic Home Point"},
    {30636, "Max altitude is set to lower than RTH altitude, aircraft will descend to the max "
            "altitude set and RTH"},
    {30638, "Obstacle avoidance failed in current flight direction and aircraft is braking. "
            "Recenter control sticks and move them again to regain control of aircraft"},
    {30639, "Collision risk detected. Active Avoidance automatically enabled. Fly with caution"},
    {30640, "Propeller guard not detected"},
    {30641, "Unable to update Dynamic Home Point. Remote controller positioning signal weak. Move "
            "to open area and wait until position is updated"},
    {30642, "Unable to refresh Dynamic Home Point. Remote controller is in Restricted Zone"},
    {30643, "Refreshing Dynamic Home Point. Remote controller is out of Restricted Zone"},
    {30644, "Lighting environment too dark"},
    {30645, "Vision sensor blurred"},
    {30646, "Remote controller positioning signal restored. Updating Dynamic Home Point..."},
    {30647, "Home Point will update in real-time to subject location"},
    {30648, "Home Point updated to current location of aircraft"},
    {30671, "For any issues, go to Find My Drone page for more help"},
    {30700, "CAAC unregistered"},
    {30701, "CAAC unregistered"},
    {30702, "CAAC unregistered"},
    {30703,
     "Battery installation error. Land immediately and ensure battery is installed properly"},
    {30710, "Designated Flyaway Aircraft"},
    {30711, "CAAC registration status information has expired"},
    {30712, "\"Unable to take off. CAAC registration information has expired. Ensure DJI Fly's "
            "internet connection is normal. Information will be updated automatically\""},
    {30713, "Make sure camera is facing subject before taking off"},
    {30714, "Aircraft arms folded"},
    {30715, "No flight available. Try taking off again in places with strong satellite positioning "
            "signal"},
    {30718, "Smart Diagnostic Mode"},
    {30720, "Take off with caution (No Position Hold mode)"},
    {30721, "Fly with caution (No Position Hold mode)"},
    {30722,
     "GNSS positioning unavailable. Wait for satellite signal to be found. Fly with caution"},
    {30723, "Home Point unavailable. Unable to return. Home Point will be updated once satellite "
            "positioning signal is regained"},
    {30725, "Vision positioning accuracy poor. Unable to return to takeoff point. Closely monitor "
            "environment ahead"},
    {30726,
     "Propeller Guard mode enabled. Make sure propeller guards are installed properly before "
     "aircraft takes off. Otherwise, abnormal flight behavior such as sudden climb or drift may "
     "occur. To disable Propeller Guard mode, go to Profile > Settings > Developer Options"},
    {30800, "Home Point updated"},
    {30801, "Reduce gimbal tilt angle to increase flight speed"},
    {30810, "Returning to palm..."},
    {30811, "Landing..."},
    {30900, "Current elevation above 3000 m (9842 ft). Fly with caution"},
    {31000, "Low battery. Aircraft returning to home. Fly with caution"},
    {31001, "Aircraft weighs over 340 g with current battery installed. Not compliant with EU "
            "regulations for C1 labeled drones"},
    {31002,
     "Propeller guard installed. Aircraft not compliant with EU regulations for C1 labeled drones"},
    {31003, "Overweight. Unable to take off. Remove propeller guard or external video transmission "
            "enhancement module and try again"},
    {31004, "Aircraft error. Do not hold aircraft or attach heavy objects during takeoff"},
    {31006, "Max flight altitude is limited because propeller guard is attached"},
    {31007, "Max flight distance is limited because propeller guard is attached"},
    {31008, "Motor temperature critically high. Return to home as soon as possible. Wait for "
            "aircraft to cool down before flying again"},
    {31009, "Motor temperature high. Return to home as soon as possible. Wait for aircraft to cool "
            "down before flying again"},
    {31010, "Overweight and insufficient power. Land as soon as possible. Do not use propeller "
            "guard with Intelligent Flight Battery Plus or DJI Cellular Dongle at the same time"},
    {40001, "Gimbal stuck"},
    {40002, "Gimbal stuck"},
    {40003, "Gimbal motor overloaded"},
    {40004, "Excessive gimbal vibration"},
    {40005, "Gimbal sensor error"},
    {40006, "Gimbal protection enabled"},
    {40007, "Excessive gimbal rotation"},
    {40010, "Gimbal initialization error"},
    {40011, "Gimbal calibration error"},
    {40012, "Incompatible gimbal data"},
    {40013, "Gimbal sensor malfunction"},
    {40014, "Gimbal ESC malfunction"},
    {40015, "Gimbal ESC malfunction"},
    {40016, "Gimbal ESC malfunction"},
    {40017, "Gimbal pan axis reached movement limit"},
    {40018, "Gimbal tilt axis reached movement limit"},
    {40019, "Gimbal roll axis reached movement limit"},
    {40021, "Incompatible gimbal IMU data. Contact DJI Support for assistance"},
    {40022, "The flight attitude angle is larger in Sport mode. The gimbal will rotate when the "
            "aircraft starts or stops. Use Normal mode if required for stable shooting"},
    {40023, "Wide-angle lens attached"},
    {40024, "Gimbal error"},
    {40026, "Gimbal overheated"},
    {40027, "Possible gimbal attitude error. Go to Settings to calibrate gimbal"},
    {40028, "Gimbal stuck. Make sure gimbal cover is removed and manually check whether gimbal can "
            "rotate freely"},
    {40029, "High wind speed detected. Aircraft body may appear in frame. Slow down to stabilize "
            "aircraft attitude"},
    {40030, "Resetting gimbal. Keep aircraft steady"},
    {40031, "Gimbal angle and flight speed may be restricted during vertical shooting to ensure "
            "view stability"},
    {40032, "High wind speed detected. Gimbal movement limit reached"},
    {40033, "Gimbal movement limit reached at current flight speed"},
    {40034,
     "High wind speed detected. Automatically adjust gimbal attitude to ensure flight safety"},
    {40036, "Resetting gimbal. Keep aircraft steady"},
    {40037, "Gimbal centering error, which may cause aircraft body to appear in frame. Calibrate"},
    {60001, "Remote controller battery level low. Recharge promptly"},
    {60005, "RC malfunction"},
    {60006, "RC malfunction"},
    {60007, "RC malfunction"},
    {60008, "RTH Failed (No Satellite Positioning Signal)"},
    {60009, "RC malfunction"},
    {60010, "RC calibration required"},
    {60011, "Power off RC"},
    {60012, "Remote controller reset. Check control stick mode and ensure there are no errors "
            "before use."},
    {60013, "Remote controller overheating. Check ambient temperature"},
    {60014, "遥控器apsrv挂死"},
    {60015, "遥控器9342挂死"},
    {60016, "No satellite positioning. Auto RTH failed. Return the aircraft to home manually"},
    {60017, "Firmware update required"},
    {60018, "Check ambient temperature to avoid overheated remote controller"},
    {60019,
     "Control sticks in wrong position. Fully extend arm. Contact DJI Support if issue persists"},
    {60020, "Remote controller temperature too low. Powering off…"},
    {60021, "Remote controller overheated. Power off or wait until temperature returns to normal"},
    {60022, "Remote controller overheated. Powering off…"},
    {60023, "Joystick error. Calibrate in settings"},
    {60024, "Battery overheated. Charging stopped"},
    {60025, "Remote controller battery level too low. Charge promptly"},
    {60050, "Controller B disconnected"},
    {60051, "Controller B disconnected"},
    {60052, "Controller A disconnected"},
    {60053, "Controller A disconnected"},
    {70629, "业务消息回调阻塞"},
    {70630, "LOCAL通道创建失败"},
    {70631, "LOCAL通道发送失败"},
    {70632, "LOCAL通道消息解析失败率过高"},
    {70633, "IP通道创建失败"},
    {70634, "IP通道消息解析失败率过高"},
    {70635, "WL通道创建失败"},
    {70636, "WL通道消息解析失败率过高"},
    {70637, "UART通道创建失败"},
    {70638, "UART通道消息解析失败率过高"},
    {70639, "CAN通道创建失败"},
    {70640, "CAN通道消息解析失败率过高"},
    {70641, "ICC通道创建失败"},
    {70642, "ICC通道消息解析失败率过高"},
    {70643, "BULK通道创建失败"},
    {70644, "BULK通道接收线程阻塞"},
    {70645, "BULK通道发送线程阻塞"},
    {70646, "BULK通道消息解析失败率过高"},
    {70647, "CAN_SOCKET通道创建失败"},
    {70648, "CAN_SOCKET通道消息解析失败率过高"},
    {70649, "SHM通道消息解析失败率过高"},
    {70650, "SHM通道创建失败"},
    {70651, "MBUS通道消息解析失败率过高"},
    {70652, "MBUS通道创建失败"},
    {70653, "Aircraft connected to USB. Paused liveview display"},
    {70654, "Disabling ECO mode… Wait a few seconds"},
    {70655, "触发日志切片，请等待日志提取完毕"},
    {80001, "No image transmission signal"},
    {80002, "Remote controller signal may be blocked. Position remote controller to face aircraft "
            "and adjust antennas for optimal signal strength or fly at higher altitude"},
    {80003, "Aircraft signal interference"},
    {80004, "Image transmission signal may be blocked. Position remote controller to face aircraft "
            "and adjust antennas for optimal signal strength or fly at higher altitude"},
    {80005, "RC signal interference"},
    {80013, "Current Wi-Fi environment experiencing high interference. Fly with caution"},
    {80014, "RC signal interference"},
    {80015, "Aircraft signal interference"},
    {80016, "Weak signal. Adjust antennas"},
    {80017, "High interference environment"},
    {80018, "Unable to use aircraft. Aircraft overheated due to being idle for extended period. "
            "Wait until aircraft cools down"},
    {80019, "Aircraft sitting for extended period. Powering off automatically. Wait until aircraft "
            "cools down"},
    {80020, "Aircraft Overheated"},
    {80021, "Aircraft Overheated"},
    {80022, "Aircraft certificate renewal required"},
    {80023, "RC certificate renewal required"},
    {80024, "Update DJI Fly"},
    {80025, "Update DJI Fly"},
    {80026, "Network error"},
    {80027, "Weak 4G signal. Fly with caution"},
    {80028, "Weak 4G signal. Fly with caution"},
    {80029, "Weak 4G signal. Fly with caution"},
    {80030, "Insufficient data allowance"},
    {80031, "Firmware update required"},
    {80032, "Firmware update required"},
    {80033, "Firmware update required"},
    {80034, "DJI Cellular Dongle update required"},
    {80035, "DJI Cellular Dongle update required"},
    {80036, "Unstable 4G signal at remote controller location"},
    {80037, "No Enhanced Trans"},
    {80038, "Weak 4G signal"},
    {80039, "Enhanced Trans exp"},
    {80040, "No internet access"},
    {80041, "No internet access"},
    {80042, "Enhanced Trans N/A"},
    {80043, "No internet access"},
    {80044, "No internet access"},
    {80045, "No internet access"},
    {80046, "No internet access"},
    {80047, "No internet access"},
    {80048, "No internet access"},
    {80049, "No internet access"},
    {80050, "SIM card N/A"},
    {80051, "SIM card N/A"},
    {80052, "No internet access"},
    {80053, "No internet access"},
    {80054, "No internet access"},
    {80055, "No internet access"},
    {80056, "No internet access"},
    {80057, "No internet access"},
    {80058, "No internet access"},
    {80059, "No internet access"},
    {80060, "No internet access"},
    {80061, "High latency in Enhanced Transmission. There may be potential delay in camera "
            "liveview. Fly with caution"},
    {80062, "Aircraft temperature high. Video transmission quality will be reduced to help cool "
            "down aircraft"},
    {80063, "Signal interference may exist between aircraft and remote controller. Position remote "
            "controller to face aircraft and adjust antennas for optimal signal strength or fly at "
            "higher altitude"},
    {80064, "Make sure no interference exists and avoid other wireless devices"},
    {80065, "Move close to aircraft and make sure no interference exists"},
    {110001, "Battery overcurrent. Maintain smooth flight and check if aircraft is overloaded"},
    {110002,
     "Battery overheating. Stop flying and wait for battery temperature to return to normal."},
    {110003, "Battery temperature too low. Warm up battery to 5°C or higher"},
    {110004, "Battery damaged"},
    {110005, "Full battery discharge and recharge cycle required. Action required to prevent "
             "in-flight accidents due to inaccurate power measurements."},
    {110006, "Non-DJI battery"},
    {110007, "Battery data communication error"},
    {110010, "Short circuit during battery discharge. Replace battery"},
    {110011, "Low battery voltage. Fly with caution"},
    {110013, "Battery power restricted. Aircraft performance decreased to ensure flight safety. "
             "Return to home promptly"},
    {110014,
     "Critical low battery. Aircraft in Auto Power Off Protection. Forced landing in progress..."},
    {110018,
     "Battery error. Land or return to home promptly. Let battery sit for 1 hr before using again"},
    {110023, "Battery temperature too low. Fly with caution"},
    {110024, "Battery error. Aircraft returning to home automatically"},
    {110025, "Battery output power insufficient. Unable to take off. Charge or replace battery"},
    {110026, "Aircraft battery voltage high. Fly with caution"},
    {110027, "Battery maintenance required. Tap title above to view details"},
    {110028, "Battery error. RTH or land promptly and restart battery"},
    {110029, "Battery error. RTH or land promptly and replace battery"},
    {110030, "Battery cycle count exceeded limit. Fly with caution"},
    {110031, "Battery cycle count approaching limit. Replace battery promptly"},
    {110032, "Unusual battery level changes. Return to home or land promptly. Discharge battery "
             "completely and fully recharge to properly maintain the battery"},
    {110033, "Battery maintenance required. Charge battery to full capacity and let battery sit "
             "for 24 hrs"},
    {110034, "Battery overheated. Aircraft propulsion will be limited"},
    {110035, "Critically low battery. Aircraft landing automatically. Use control sticks to help "
             "aircraft avoid obstacles or adjust landing position"},
    {110036, "Aircraft battery depleted. Auto landing in progress. Use control sticks to move "
             "aircraft horizontally to avoid obstacles or adjust landing position"},
    {110037, "Low battery. Return to home promptly"},
    {110038, "Low battery"},
    {110039, "Charge or warm up battery"},
    {180001, "Forward vision sensor calibration error. Auto calibration in progress..."},
    {180002, "Backward vision sensor calibration error. Auto calibration in progress..."},
    {180003, "Downward vision sensor error"},
    {180004, "Left vision sensor calibration error. Contact DJI Support"},
    {180005, "Right vision sensor calibration error. Contact DJI Support"},
    {180006, "Upward vision sensor calibration error. Auto calibration in progress..."},
    {180007, "Vision System Calibration Required"},
    {180008, "Vision System Calibration Required"},
    {180016, "Downward vision sensor error. Contact DJI Support for assistance"},
    {180017, "Downward vision sensor error. Contact DJI Support for assistance"},
    {180018, "Forward vision sensor error. Contact DJI Support for assistance"},
    {180019, "Forward vision sensor error. Contact DJI Support for assistance"},
    {180020, "Downward vision sensor error. Contact DJI Support for assistance"},
    {180026, "Vision sensor error. Contact DJI Support for assistance"},
    {180027, "Vision sensor error. Contact DJI Support for assistance"},
    {180028, "Vision sensor error. Contact DJI Support for assistance"},
    {180029, "Vision sensor error. Contact DJI Support for assistance"},
    {180030, "Vision sensor error. Contact DJI Support for assistance"},
    {180031, "Vision sensor error. Contact DJI Support for assistance"},
    {180032, "Lighting environment too dark. Visual positioning inaccurate. Fly with caution"},
    {180033, "Downward vision sensor calibration error. Contact DJI Support for assistance"},
    {180034, "Backward vision sensor error. Contact DJI Support for assistance"},
    {180035, "Backward vision sensor error. Contact DJI Support for assistance"},
    {180036, "Lighting environment too bright. Vision System unavailable. Fly with caution"},
    {180037, "Vision system and obstacle avoidance are unavailable due to insufficient ambient "
             "light. Pay attention to surroundings"},
    {180038, "Vision sensor(s) blocked. Fly with caution"},
    {180039, "Infrared sensor error. Contact DJI Support for assistance"},
    {180043, "Upward vision sensor error. Contact DJI Support"},
    {180044, "Upward vision sensor error. Contact DJI Support"},
    {180045, "Vision sensor(s) blurry. Vision system unavailable. Clean sensor lens"},
    {180046, "Ambient light too bright. Vision system unavailable. Fly with caution"},
    {180047, "Vision system and obstacle avoidance are unavailable due to insufficient ambient "
             "light. Pay attention to surroundings"},
    {180048, "Vision System Calibration Required"},
    {180051, "Left vision sensor error. Contact DJI Support"},
    {180052, "Left vision sensor error. Contact DJI Support"},
    {180053, "Right vision sensor error. Contact DJI Support"},
    {180054, "Right vision sensor error. Contact DJI Support"},
    {180055, "Low visibility. Fly with caution"},
    {180056, "Unstable lighting conditions. Vision system and obstacle avoidance unavailable. Fly "
             "with caution"},
    {180057, "Vision system and obstacle avoidance unavailable. Hyperlapse paused. Fly in open "
             "area to resume shooting"},
    {180058, "Vision system and obstacle avoidance unavailable. Unable to use Point of Interest"},
    {180059, "Aircraft not in flight. Vision systems and obstacle avoidance disabled"},
    {180060, "Vision System Calibration Required"},
    {180061, "Downward ToF sensor error"},
    {180062, "Forward ToF sensor error"},
    {180063, "Backward ToF sensor error"},
    {180064, "Upward ToF sensor error"},
    {180065, "Left ToF sensor error"},
    {180066, "Right ToF sensor error"},
    {180067, "Downward ToF sensor error"},
    {180068, "Forward ToF sensor error"},
    {180069, "Backward ToF sensor error"},
    {180070, "Upward ToF sensor error"},
    {180071, "Left ToF sensor error"},
    {180072, "Right ToF sensor error"},
    {180073, "Power mode error. Restart aircraft"},
    {180074, "Downward vision sensor calibration error. Auto calibration in progress..."},
    {180075, "Lighting environment too bright. Unable to hover precisely. Fly with caution"},
    {180076, "Lighting environment too dark. Unable to hover precisely. Fly with caution"},
    {180079, "Downward IR vision sensor blurred. Clean sensor lens and restart aircraft"},
    {180080, "Forward LiDAR blurred. Clean LiDAR and restart aircraft"},
    {180081,
     "Overexposed. Vision system and obstacle avoidance affected. Pay attention to surroundings"},
    {180082,
     "Underexposed. Vision system and obstacle avoidance affected. Pay attention to surroundings"},
    {180083, "Obstacle avoidance unavailable. Pay attention to surroundings and fly in textured "
             "environment"},
    {180084, "Obstacle sensing unavailable during high-speed flight. Fly with caution"},
    {180085, "Vision system and obstacle avoidance are unavailable due to insufficient ambient "
             "light. Pay attention to surroundings"},
    {800002, "QuickShots interrupted. Aircraft hovering"},
    {800003, "QuickShot complete. Aircraft returning to task start point"},
    {800004, "Max flight altitude reached. Adjust altitude and try again"},
    {800005, "Max flight distance reached. Adjust distance and try again"},
    {800006, "Task timed out. Check and try again"},
    {800007, "Satellite positioning signal weak. Wait a moment and try again"},
    {800008, "Control stick moved. Exited QuickShot"},
    {800009, "QuickShot initialization failed. Check and try again"},
    {800010, "Camera mode error. Retry QuickShot"},
    {800012, "Camera mode error. Retry QuickShot"},
    {800013, "Obstacle detected. QuickShot ended"},
    {800014, "QuickShot stopped"},
    {800015, "Gimbal stuck. Check gimbal"},
    {800016, "Control acquisition failed. QuickShots stopped"},
    {800017, "Insufficient storage. QuickShots stopped"},
    {800018, "Subject lost. Select subject again"},
    {800019, "Shooting Asteroid failed. QuickShot ended"},
    {800020, "Creating Asteroid failed. QuickShot ended"},
    {800021, "Loading calibration parameters failed. QuickShots stopped"},
    {800022, "Adjusting camera parameters failed. QuickShots stopped"},
    {800023, "Shooting Asteroid timed out. QuickShot ended"},
    {800024, "Flight mode error. Exited QuickShots"},
    {800028, "Aircraft landing automatically. Exited QuickShots"},
    {800029, "Aircraft returning to home automatically. Exited QuickShots"},
    {800030, "Insufficient storage. Exited QuickShots"},
    {800101, "拍摄失败"},
    {800103, "当前拍摄状态错误，请重新尝试"},
    {800104, "当前拍摄状态错误，请重新尝试"},
    {800105, "当前拍摄状态错误，请重新尝试"},
    {800107, "Panorama failed. Check and try again"},
    {800108, "Panorama failed. Check and try again"},
    {800109, "Panorama timed out. Check and try again"},
    {800110, "Unable to use Pano. Check and try again"},
    {800111, "Aircraft storage insufficient. Unable to shoot. Free up storage space and try again"},
    {800112,
     "Aircraft moving. Unable to start shooting. Wait for aircraft to stabilize and try again"},
    {800113, "Gimbal moving. Unable to start shooting. Wait for gimbal to stabilize and try again"},
    {800114, "Control stick moved. Panorama stopped"},
    {800115, "Max flight altitude reached. Unable to start shooting. Adjust aircraft altitude and "
             "try again"},
    {800116, "Max flight distance reached. Unable to start shooting. Adjust aircraft distance and "
             "try again"},
    {800117, "Gimbal stuck. Check and ensure gimbal can rotate freely"},
    {800118, "Panorama failed. Check and try again"},
    {800119, "Creating panorama failed"},
    {800120, "Loading camera settings failed. Check and try again"},
    {800121, "Saving camera settings failed. Check and try again"},
    {800122, "Strong wind. Panorama stopped"},
    {800123, "Strong wind. Error may occur during pano stitching"},
    {800201, "Control stick moved. Hyperlapse stopped"},
    {800202, "Remote controller disconnected. Hyperlapse stopped"},
    {800204, "Hyperlapse failed. Check and try again"},
    {800205, "Hyperlapse failed. Check and try again"},
    {800207, "Aircraft in Restricted Zone. Unable to use Hyperlapse"},
    {800208, "Aircraft max flight distance reached. Hyperlapse exited"},
    {800209, "Aircraft max altitude reached. Hyperlapse exited"},
    {800211, "Insufficient storage. Unable to increase shooting duration"},
    {800215, "Insufficient storage. Unable to increase shooting duration"},
    {800216, "Task timed out. Check and restart Hyperlapse"},
    {800217, "Hyperlapse failed. Check and try again"},
    {800218, "Hyperlapse failed. Check and try again"},
    {800219, "Shooting status error. Check and try again"},
    {800220, "Insufficient storage space. Unable to create video"},
    {800221, "Camera parameter error. Check and try again"},
    {800222, "Shooting status error. Check and try again"},
    {800223, "Shooting status error. Check and try again"},
    {800224, "Shooting status error. Check and try again"},
    {800226, "Rendering video failed"},
    {800237, "Aircraft landing automatically. Exited Hyperlapse"},
    {800238, "Aircraft returning to home automatically. Exited Hyperlapse"},
    {800301, "Min flight altitude reached. Aircraft unable to continue descending"},
    {800302, "Max flight altitude reached. Aircraft unable to continue ascending"},
    {800303, "Horizontal distance to subject too short"},
    {800304, "Subject too far"},
    {800310, "Aircraft altitude too low. Adjust altitude and switch to ActiveTrack"},
    {800311, "Aircraft altitude too high. Adjust altitude and switch to ActiveTrack"},
    {800312, "Horizontal distance to subject too short. Adjust distance and switch to ActiveTrack"},
    {800313, "Subject too far. Adjust distance and switch to ActiveTrack"},
    {800314, "Subject moving too fast. Switch to Sport mode to increase following speed. Note: "
             "Obstacle avoidance unavailable in Sport mode"},
    {800322, "Subject may have changed. Check before starting ActiveTrack"},
    {800324, "Measuring subject distance failed. Check and try again"},
    {800325, "Subject too close to aircraft. Restart Follow Mode"},
    {800341, "Subject lost. Reselect subject"},
    {800342, "Measuring subject distance failed. Check and try again"},
    {800343, "Measuring subject distance failed. Reselect subject"},
    {800344, "Subject lost. Follow Mode exited"},
    {800348,
     "Aircraft impact detected. Ensure current environment is safe before continuing operation"},
    {800349, "Aircraft altitude too low. Increase altitude and reselect subject"},
    {800350, "Aircraft altitude too high. Decrease altitude and reselect subject"},
    {800351, "Horizontal distance to subject too short. Fly farther away and reselect subject"},
    {800352, "Aircraft too far from subject. Move closer to subject"},
    {800361, "Aircraft in GEO Zone. Unable to use FocusTrack"},
    {800362, "Retry FocusTrack"},
    {800366, "Flight control status error. Retry FocusTrack"},
    {800367, "Aircraft landing automatically. Exited FocusTrack"},
    {800368, "Aircraft returning to home automatically. Exited FocusTrack"},
    {800369, "Lighting in current environment too dark. Unable to use ActiveTrack"},
    {800370, "Lighting in current environment too bright. Unable to use ActiveTrack"},
    {800372, "Too close to obstacle. Subject following ended"},
    {800373, "Distance to object below aircraft too close. POI stopped"},
    {800374, "Measuring subject distance. Unable to switch shooting modes"},
    {800376, "Vision system and obstacle avoidance unavailable. Unable to use Point of Interest"},
    {800377, "Aircraft approaching max flight altitude. Unable to use FocusTrack. Fly aircraft at "
             "lower altitude and try again"},
    {800381, "Commission Delegated Regulation (EU) 2019/945 requires aircraft to stay within a 50m "
             "range when tracking. Unable to continue ActiveTrack. Fly aircraft closer or reduce "
             "speed of tracked subject and try again"},
    {800382, "Unable to use Subject Scanning when using tele camera. Subject Scanning disabled"},
    {800910, "Low-light stabilized flight enabled to ensure image quality"},
    {800911, "Vision positioning and obstacle sensing disabled"},
    {800912, "Descent Speed Limited"},
    {800913, "Vision positioning and obstacle sensing disabled"},
    {800914, "Low ambient light"},
    {900001, "Aircraft not connected to RC"},
    {900002, "RC not connected to mobile device"},
};

} // namespace

std::optional<std::string> diagcode_text(int code) {
    auto it = kDiagText.find(code);
    if (it == kDiagText.end())
        return std::nullopt;
    return std::string(it->second);
}

} // namespace djilink
